/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gestion_Stock;


import java.awt.Dimension;
import java.awt.Toolkit;
import static java.lang.Double.parseDouble;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class BonSortie extends javax.swing.JFrame {

    /**
     * Creates new form BonSortie
     */
    ResultSet Rs;
    DefaultTableModel modele = new DefaultTableModel();
    
    public BonSortie() {
        
        connect();
        initComponents();
        jImprimer.setEnabled(false);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Date aujourdhui = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        
        jDate.setText(format.format(aujourdhui));
        /*Dimension tailleMoniteur = Toolkit.getDefaultToolkit().getScreenSize();
        int longueur = tailleMoniteur.width * 1/2;
        int hauteur = tailleMoniteur.height * 2/3;
        //régler la taille de JFrame à 2/3 la taille de l'écran
        this.setSize(longueur, hauteur);*/
        this.setLocationRelativeTo(null);
        modele.addColumn("service");
        modele.addColumn("Nom Du Signataire");
        modele.addColumn("Désignation");
        modele.addColumn("Quantité");
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nrbdd" ,"root","");
            PreparedStatement stm = conn.prepareStatement("SELECT MAX(num) from bonsortie  ");
            ResultSet rs = stm.executeQuery();
            if(rs.next()){
            int num = rs.getInt("num");
            Jnum.setText("" + num+1);
            
                
            }else{
                JOptionPane.showMessageDialog(null, "erreur");
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
        
        
        
        
        
    }
    public void connect(){
        try{
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nrbdd" ,"root","");
            System.out.println("connection succeed!");
        }catch(Exception e ){
            System.err.println(""+e);
        }
        
    }
    public void Afficher(){
       
        try{
            String service = (String) jTService.getSelectedItem();
            String nom = jTNom.getText();
            String désignation = jTDésingation.getText();
            String quantité = jTQuantité.getText();
            
            modele.addRow(new Object[] {service , nom,désignation ,quantité });
           
        }catch(Exception e ){
            System.err.println(e);
        }
       jTable1.setModel(modele);
        
    }
    
    public void Sélectioner(){
        try{
            
            int selct = jTable1.getSelectedRow();
            DefaultTableModel model =(DefaultTableModel)jTable1.getModel();
            jTService.setSelectedItem(model.getValueAt(selct, 0).toString());
            jTNom.setText(model.getValueAt(selct, 1).toString());
            jTDésingation.setText(model.getValueAt(selct, 2).toString());
            jTQuantité.setText(model.getValueAt(selct, 3).toString());
            //jTQuantité.setColumns((int) model.getValueAt(selct, 3));
        }catch(Exception e){
            System.err.println(e);
        }
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTDésingation = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTQuantité = new javax.swing.JTextField();
        jTService = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jAjouter = new javax.swing.JButton();
        jModifier = new javax.swing.JButton();
        jSupprimer = new javax.swing.JButton();
        jNouveau = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jImprimer = new javax.swing.JButton();
        jTermier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Jnum = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setToolTipText("");

        jLabel2.setText("Service Moyens Généraux");

        jLabel3.setText("FACULTE DES SIENCES EXACTES ET DE L'INFORMATIQUE ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BON DE SORTIE");

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Service De:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nom Du Signataire:");

        jTNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTNomKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Désignation");

        jTDésingation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDésingationActionPerformed(evt);
            }
        });
        jTDésingation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDésingationKeyPressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Accorde/Quantité");

        jTQuantité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQuantitéActionPerformed(evt);
            }
        });
        jTQuantité.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTQuantitéKeyPressed(evt);
            }
        });

        jTService.setEditable(true);
        jTService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secrétariat Générale", "Evaluation", "Scolarité", "Orientation et Statistique", "Activités de Recherche", "Rlations et Coopération ", "Formation Superieur", "Comptabilité et Finances ", "utilisateurs", "Activités Culturelles", "Bibliothéque", "Moyens Généraux", "Magasin" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTNom)
                            .addComponent(jTDésingation, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(jTQuantité)
                            .addComponent(jTService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTDésingation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9))
                    .addComponent(jTQuantité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service", "Nom Du Signataire", "Désignation", "Quantité"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.setUpdateSelectionOnSort(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Service");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Nom Du Signataire");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Désignation");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Quantité");
        }

        jDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDate.setText("jLabel10");

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jAjouter.setBackground(new java.awt.Color(0, 102, 102));
        jAjouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAjouter.setText("Ajouter");
        jAjouter.setToolTipText("");
        jAjouter.setAutoscrolls(true);
        jAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAjouterActionPerformed(evt);
            }
        });

        jModifier.setBackground(new java.awt.Color(0, 102, 102));
        jModifier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jModifier.setText("Modifier");
        jModifier.setPreferredSize(new java.awt.Dimension(79, 23));
        jModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModifierActionPerformed(evt);
            }
        });

        jSupprimer.setBackground(new java.awt.Color(0, 102, 102));
        jSupprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSupprimer.setText("Supprimer");
        jSupprimer.setMaximumSize(new java.awt.Dimension(79, 23));
        jSupprimer.setMinimumSize(new java.awt.Dimension(79, 23));
        jSupprimer.setPreferredSize(new java.awt.Dimension(79, 23));
        jSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimerActionPerformed(evt);
            }
        });

        jNouveau.setBackground(new java.awt.Color(0, 102, 102));
        jNouveau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jNouveau.setText("Nouveau");
        jNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNouveauActionPerformed(evt);
            }
        });

        jSave.setBackground(new java.awt.Color(0, 102, 102));
        jSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSave.setText("Sauvegarder");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Stock");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jImprimer.setBackground(new java.awt.Color(0, 102, 102));
        jImprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jImprimer.setText("Imprimer");
        jImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jImprimerActionPerformed(evt);
            }
        });

        jTermier.setBackground(new java.awt.Color(0, 102, 102));
        jTermier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTermier.setText("Terminer");
        jTermier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTermierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jNouveau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTermier, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jImprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jModifier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSupprimer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jAjouter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jTermier, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jLabel1.setText("MOSTAGANEM");

        Jnum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jnum.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Jnum, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(338, 338, 338)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDate)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(278, 278, 278))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setName(""); // NOI18N

        jMenu1.setText("Fichier");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Nouveau");
        jMenu1.add(jMenuItem5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Sauvegarder");
        jMenu1.add(jMenuItem4);

        jMenuItem9.setText("revenir à la page d'acceuil");
        jMenu1.add(jMenuItem9);

        jMenuItem6.setText("Sortir");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Ajouter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Modifier");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Supprimer");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Articles");

        jMenuItem7.setText("Voir Stock");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDésingationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDésingationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDésingationActionPerformed

    private void jAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAjouterActionPerformed
       
        //String service = jTService.getText();
       
        String nom = jTNom.getText();
        String désignation = jTDésingation.getText();
        String quantité = jTQuantité.getText();
        if( nom.equals("") || désignation.equals("") || quantité.equals("")){
            JOptionPane.showMessageDialog(null,"Completez vos Informations !");
        }else{
            
             Afficher();
        }
       
    }//GEN-LAST:event_jAjouterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       try{
           int clicked = jTable1.getSelectedRow();
           Sélectioner();
           
       }catch(Exception e ){
           System.err.println(e);
       }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
         int i =jTable1.getSelectedRow();
         if(i!=-1){
             modele.removeRow(i);
         }else{
             JOptionPane.showMessageDialog(null,"Choisir une ligne puis le supprimer! ");
         }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int i =jTable1.getSelectedRow();
        if(i!=-1){
            Sélectioner();
        }else{
            JOptionPane.showMessageDialog(null,"Sélectionner une ligne et le Modifier ! ");
        }
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jTService.setSelectedItem("");
        jTNom.setText("");
        jTDésingation.setText("");
        jTQuantité.setText("");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNouveauActionPerformed
        jTService.setSelectedItem("");
        jTNom.setText("");
        jTDésingation.setText("");
        jTQuantité.setText("");
    }//GEN-LAST:event_jNouveauActionPerformed

    private void jModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModifierActionPerformed
        int i =jTable1.getSelectedRow();
        if(i!=-1){
            Sélectioner();
            String service = (String)jTService.getSelectedItem();
            String nom = jTNom.getText();
            String désignation = jTDésingation.getText();
            String quantité = jTQuantité.getText();
            
        if( nom.equals("") || désignation.equals("") || quantité.equals("")){
            JOptionPane.showMessageDialog(null,"Completez vos Informations !");
        }else{
             modele.removeRow(i);
            Afficher();
             
             
        }
        }else{
            JOptionPane.showMessageDialog(null,"Sélectionner une ligne et le Modifier ! ");
        }
    }//GEN-LAST:event_jModifierActionPerformed

    private void jSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupprimerActionPerformed
         int i =jTable1.getSelectedRow();
         if(i!=-1){
             modele.removeRow(i);
         }else{
             JOptionPane.showMessageDialog(null,"Choisir une ligne puis le supprimer! ");
         }
    }//GEN-LAST:event_jSupprimerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
       try{
           if(jTService.equals("") || jTNom.equals("") || jTDésingation.equals("") || jTQuantité.equals("")){
               JOptionPane.showMessageDialog(null,"Completez vos informations!");
           }
           
        boolean b = false ; 
           
       for(int j=0; j<modele.getRowCount(); j++){
           if((jTDésingation.getText()).equals(modele.getValueAt(j, 0)) ){
               b=true; 
               break ; 
           }
       }
       if(b==false){
           DefaultTableModel model =(DefaultTableModel)jTable1.getModel(); 
           for(int row=0; row<modele.getRowCount(); row++){
            
           
            String service = model.getValueAt(row, 0).toString();
            String nom = model.getValueAt(row, 1).toString();
            String des = model.getValueAt(row, 2).toString();
            String qte = model.getValueAt(row, 3).toString();
           Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nrbdd" ,"root","");
           String query = ("INSERT INTO  `bonsortie` ( `service`, `nom_signataire`, `designation`, `quantite`) values (?,?,?,?)");
           PreparedStatement insert = conn.prepareStatement(query);
           insert.setString(1, (String) service );
           insert.setString(2, nom );
           insert.setString(3, des );
           insert.setString(4, qte );
           int rowsAffected = insert.executeUpdate();
           
           
           jTService.setSelectedItem("");
           jTNom.setText("");
           jTDésingation.setText("");
           jTQuantité.setText("");
           }
           JOptionPane.showMessageDialog(null,"Enregistremant");
     
       }else{
            JOptionPane.showMessageDialog(null,"Déja Enregistré!");
       }
       
           
       }catch(Exception e ){
           System.err.println(e);
       }
    }//GEN-LAST:event_jSaveActionPerformed

    private void jImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jImprimerActionPerformed
       
    }//GEN-LAST:event_jImprimerActionPerformed

    private void jTQuantitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQuantitéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTQuantitéActionPerformed

    private void jTermierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTermierActionPerformed
        try{
            
            for(int row=0; row<modele.getRowCount(); row++){
                
                String service = modele.getValueAt(row, 0).toString();
                String nom = modele.getValueAt(row, 1).toString();
                String des = modele.getValueAt(row, 2).toString();
                String  qte =modele.getValueAt(row, 3).toString();
                
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/nrbdd" ,"root","");
      
            PreparedStatement stm = conn.prepareStatement("SELECT * from stock where des=? ");
            stm.setString(1, des);         
            ResultSet rs = stm.executeQuery();
            if(rs.next()){
                int old =  rs.getInt("qua");
                int qt = Integer.parseInt(qte);
                int nv = old - qt ;
            if(old!=0 && old>0 && old>=qt){
                
               PreparedStatement update = conn.prepareStatement("UPDATE stock SET  qua=? WHERE des=? ");
               update.setInt(1,nv);
               update.setString(2,des);
               int numRowsUpdated = update.executeUpdate();
            if(numRowsUpdated>0){
                System.out.println("terminer");
            }else{
                JOptionPane.showMessageDialog(null,"echec!");
            }
            }else{
                JOptionPane.showMessageDialog(null, "Stock insuffisant!");
            }
              
           
            
            }else{
                JOptionPane.showMessageDialog(null,"élement indisponible dans le stock ou bien saisie incorrecte");
            }
                
            }
            
           
            
        }catch(Exception e ){
            System.err.print(e);
        }
    }//GEN-LAST:event_jTermierActionPerformed

    private void jTQuantitéKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTQuantitéKeyPressed
        char cart =evt.getKeyChar();
        if(Character.isLetter(cart)){
             
            jTQuantité.setEditable(false);
            
        }else{
            jTQuantité.setEditable(true);
            
        }
    }//GEN-LAST:event_jTQuantitéKeyPressed

    private void jTDésingationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDésingationKeyPressed
       char c =evt.getKeyChar();
       if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            //saiser juste les lettres
            jTDésingation.setEditable(true);
            // messge errur

        }else{
            jTDésingation.setEditable(false);
            // messge errur

            
        }
         
    }//GEN-LAST:event_jTDésingationKeyPressed

    private void jTNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNomKeyPressed
       
        char c =evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            //saiser juste les lettres
            jTNom.setEditable(true);
    }//GEN-LAST:event_jTNomKeyPressed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BonSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BonSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BonSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BonSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BonSortie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jnum;
    private javax.swing.JButton jAjouter;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jDate;
    private javax.swing.JButton jImprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JButton jModifier;
    private javax.swing.JButton jNouveau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSupprimer;
    private javax.swing.JTextField jTDésingation;
    private javax.swing.JTextField jTNom;
    private javax.swing.JTextField jTQuantité;
    private javax.swing.JComboBox<String> jTService;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTermier;
    // End of variables declaration//GEN-END:variables
}
